# Generated by Django 4.2.5 on 2023-10-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_bulk_price_product_rate_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
