# Generated by Django 4.2.5 on 2023-10-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mfd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
