# Generated by Django 4.2.5 on 2023-10-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packet',
            field=models.IntegerField(default=0),
        ),
    ]
