# Generated by Django 4.2.6 on 2023-11-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_sale_delete_customer_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cart',
            field=models.ForeignKey(blank=True, default='Single Item Sale', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
    ]
