# Generated by Django 4.2.6 on 2023-11-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_sale_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
    ]
