# Generated by Django 5.1.1 on 2024-10-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packet',
            field=models.IntegerField(default=1),
        ),
    ]
