# Generated by Django 5.1.1 on 2024-10-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_profit_alter_product_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
