# Generated by Django 5.1.1 on 2024-10-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_profit_alter_product_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='cartItem',
        ),
    ]
