# Generated by Django 5.1.6 on 2025-03-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_image_alter_product_packet_contain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profit',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='item_sale_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='num_packet',
            new_name='num_of_packages',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='packet_contain',
            new_name='package_contain',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bulk_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_purchase_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_sale_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_items',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_package_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
