# Generated by Django 5.1.6 on 2025-03-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_product_image_alter_product_packet_contain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfd',
        ),
    ]
