# Generated by Django 5.1.6 on 2025-03-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_expd_remove_product_mfd'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
