# Generated by Django 5.1.6 on 2025-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_sale_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_sale_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
