# Generated by Django 5.1.6 on 2025-03-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_item_sale_price_product_package_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='bulk_price',
            new_name='package_purchase_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='total_price',
        ),
    ]
