# Generated by Django 5.1.6 on 2025-03-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_rename_bulk_price_product_package_purchase_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_packet',
            new_name='num_packages',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='packet_contain',
            new_name='package_content',
        ),
        migrations.AlterField(
            model_name='product',
            name='package_purchase_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
