# Generated by Django 5.1.6 on 2025-03-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_rename_num_packet_product_num_packages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_packages',
            new_name='num_of_packages',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='package_content',
            new_name='package_contain',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='profit',
            new_name='total_items',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='total_package_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
